### ISSUE TITLE
Does not support python 3.8!!!!

### ISSUE THREAD

**Issue by daveusa31** [1ort/aiolava#4]
Perhaps it is worth removing the specific syntax for python (3.9 or 3.10), so that there is support for python 3.6?

**Comment by 1ort** [comment]
What exactly do you mean? Type hints?

**Comment by daveusa31** [comment]
Yes, for the wallet_list method, replace ```Dict | list``` with ```typing.Union[Dict, list]```

**Comment by 1ort** [comment]
Do not need | or union at all at this function. Fixed
